#!/usr/bin/env bash
# Script that configures an Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts 
